n1:
        bind: 127.0.0.1
        port: 7701
n2:
        bind: 127.0.0.1
        port: 7702
n3:
        bind: 127.0.0.1
        port: 7703
n4:
        bind: 127.0.0.1
        port: 7704
n5:
        bind: 127.0.0.1
        port: 7705
n6:
        bind: 127.0.0.1
        port: 7706
n7:
        bind: 127.0.0.1
        port: 7707
